export const config = {
  port: Number.parseInt(process.env.PORT ?? '4000', 10),
  todoStorage: process.env.TODO_STORAGE ?? 'file',
  todoFile: process.env.TODO_FILE ?? '/var/lib/vigor-workbench/todos.json',
  salesFile: process.env.SALES_FILE ?? '/var/lib/vigor-workbench/sales.json',
  auditFile: process.env.AUDIT_FILE ?? '/var/lib/vigor-workbench/audit.jsonl',
  databaseUrl: process.env.DATABASE_URL,
  databaseSsl: process.env.DATABASE_SSL === 'true',
  databaseSslCaPath: process.env.DATABASE_SSL_CA_PATH,
  databaseSslServername: process.env.DATABASE_SSL_SERVERNAME,
  demoMode: (process.env.DEMO_MODE ?? 'true') === 'true',
  allowedOrigins: (process.env.ALLOWED_ORIGINS ?? 'http://1.15.91.150').split(',').map(value => value.trim()).filter(Boolean),
  bridgeSecret: process.env.WORKBENCH_BRIDGE_SECRET ?? '',
  integrationFile: process.env.INTEGRATION_FILE ?? '/var/lib/vigor-workbench/integrations.json',
  userFile: process.env.USER_FILE ?? '/var/lib/vigor-workbench/users.json',
  appPermissionsFile: process.env.APP_PERMISSIONS_FILE ?? '/var/lib/vigor-workbench/app-permissions.json',
  authSecret: process.env.WORKBENCH_AUTH_SECRET ?? process.env.WORKBENCH_BRIDGE_SECRET ?? '',
  bootstrapAdminPassword: process.env.BOOTSTRAP_ADMIN_PASSWORD,
  orgPickerToken: process.env.ORG_PICKER_TOKEN ?? '',
}
